// game/questions.ts
import type { Question } from './types';

const geografia: Question[] = [
  { subject: 'geografia', question: 'Qual é a capital da França?', options: ['Berlim', 'Madri', 'Paris', 'Roma'], answer: 'Paris' },
  { subject: 'geografia', question: 'Qual é a capital do Brasil?', options: ['Brasília', 'Rio de Janeiro', 'São Paulo', 'Salvador'], answer: 'Brasília' },
  { subject: 'geografia', question: 'Qual o oceano mais profundo do mundo?', options: ['Atlântico', 'Índico', 'Ártico', 'Pacífico'], answer: 'Pacífico' },
  { subject: 'geografia', question: 'Qual é o maior oceano do mundo?', options: ['Atlântico', 'Índico', 'Ártico', 'Pacífico'], answer: 'Pacífico' },
  { subject: 'geografia', question: 'Qual a montanha mais alta do mundo?', options: ['Monte Everest', 'K2', 'Kangchenjunga', 'Lhotse'], answer: 'Monte Everest' },
  { subject: 'geografia', question: 'Qual é o rio mais longo do mundo?', options: ['Rio Nilo', 'Rio Amazonas', 'Rio Yangtzé', 'Rio Mississippi'], answer: 'Rio Amazonas' },
  { subject: 'geografia', question: 'Quantos estados tem o Brasil?', options: ['25', '26', '27', '28'], answer: '26' },
  { subject: 'geografia', question: 'Qual o nome do deserto mais quente do mundo?', options: ['Deserto do Saara', 'Deserto do Atacama', 'Deserto da Arábia', 'Deserto de Gobi'], answer: 'Deserto do Saara' },
  { subject: 'geografia', question: 'Qual é a capital da Austrália?', options: ['Sydney', 'Melbourne', 'Camberra', 'Perth'], answer: 'Camberra' },
  { subject: 'geografia', question: 'Qual o país que tem a forma de uma bota?', options: ['França', 'Itália', 'Grécia', 'Espanha'], answer: 'Itália' },
  { subject: 'geografia', question: 'Qual o ponto mais alto da África?', options: ['Monte Kilimanjaro', 'Monte Quênia', 'Montanhas Atlas', 'Monte Ruwenzori'], answer: 'Monte Kilimanjaro' },
  { subject: 'geografia', question: 'Qual o maior país do mundo em extensão territorial?', options: ['Estados Unidos', 'China', 'Canadá', 'Rússia'], answer: 'Rússia' },
  { subject: 'geografia', question: 'Qual é a capital do Japão?', options: ['Pequim', 'Tóquio', 'Seul', 'Bangkok'], answer: 'Tóquio' },
  { subject: 'geografia', question: 'Em qual continente fica o Egito?', options: ['Ásia', 'África', 'Europa', 'Oceania'], answer: 'África' },
  { subject: 'geografia', question: 'Qual o menor país do mundo?', options: ['Mônaco', 'San Marino', 'Vaticano', 'Malta'], answer: 'Vaticano' },
  { subject: 'geografia', question: 'Qual a capital da Argentina?', options: ['Santiago', 'Buenos Aires', 'Montevidéu', 'Assunção'], answer: 'Buenos Aires' },
  { subject: 'geografia', question: 'Qual é a capital do Egito?', options: ['Cairo', 'Alexandria', 'Luxor', 'Gizé'], answer: 'Cairo' },
  { subject: 'geografia', question: 'Qual canal liga o Atlântico ao Pacífico?', options: ['Canal de Suez', 'Canal do Panamá', 'Canal da Mancha', 'Estreito de Bering'], answer: 'Canal do Panamá' },
  { subject: 'geografia', question: 'Qual cidade italiana é famosa pelos canais e gôndolas?', options: ['Roma', 'Florença', 'Veneza', 'Milão'], answer: 'Veneza' },
  { subject: 'geografia', question: 'Qual estado brasileiro tem a maior área territorial?', options: ['Pará', 'Amazonas', 'Mato Grosso', 'Minas Gerais'], answer: 'Amazonas' },
];

const historia: Question[] = [
  { subject: 'historia', question: 'Em que ano o homem pisou na Lua pela primeira vez?', options: ['1969', '1972', '1965', '1980'], answer: '1969' },
  { subject: 'historia', question: 'Qual o nome do primeiro homem a viajar para o espaço?', options: ['Neil Armstrong', 'Yuri Gagarin', 'Buzz Aldrin', 'John Glenn'], answer: 'Yuri Gagarin' },
  { subject: 'historia', question: 'Quem foi o primeiro presidente do Brasil?', options: ['Dom Pedro I', 'Marechal Deodoro da Fonseca', 'Getúlio Vargas', 'Prudente de Morais'], answer: 'Marechal Deodoro da Fonseca' },
  { subject: 'historia', question: 'Quem descobriu o Brasil?', options: ['Cristóvão Colombo', 'Pedro Álvares Cabral', 'Vasco da Gama', 'Fernão de Magalhães'], answer: 'Pedro Álvares Cabral' },
  { subject: 'historia', question: 'Em que ano caiu o Muro de Berlim?', options: ['1985', '1989', '1991', '1993'], answer: '1989' },
  { subject: 'historia', question: 'Quem foi o primeiro imperador do Brasil?', options: ['Dom João VI', 'Dom Pedro I', 'Dom Pedro II', 'Marechal Deodoro'], answer: 'Dom Pedro I' },
  { subject: 'historia', question: 'Em que ano começou a Segunda Guerra Mundial?', options: ['1914', '1929', '1939', '1945'], answer: '1939' },
  { subject: 'historia', question: 'Em que ano foi proclamada a Independência do Brasil?', options: ['1808', '1822', '1888', '1889'], answer: '1822' },
  { subject: 'historia', question: 'Quem foi o primeiro presidente dos Estados Unidos?', options: ['Thomas Jefferson', 'George Washington', 'Abraham Lincoln', 'Benjamin Franklin'], answer: 'George Washington' },
  { subject: 'historia', question: 'Em que ano foi abolida a escravidão no Brasil?', options: ['1822', '1850', '1888', '1889'], answer: '1888' },
  { subject: 'historia', question: 'Qual civilização construiu Machu Picchu?', options: ['Astecas', 'Maias', 'Incas', 'Olmecas'], answer: 'Incas' },
  { subject: 'historia', question: 'Qual líder comandou a Alemanha nazista?', options: ['Joseph Stalin', 'Benito Mussolini', 'Adolf Hitler', 'Franco'], answer: 'Adolf Hitler' },
  { subject: 'historia', question: 'Qual princesa brasileira assinou a Lei Áurea?', options: ['Princesa Leopoldina', 'Princesa Isabel', 'Princesa Maria', 'Princesa Carlota'], answer: 'Princesa Isabel' },
  { subject: 'historia', question: 'Quem ficou conhecido como o líder da Inconfidência Mineira?', options: ['Zumbi dos Palmares', 'Tiradentes', 'José Bonifácio', 'Frei Caneca'], answer: 'Tiradentes' },
  { subject: 'historia', question: 'Em que século aconteceu a Revolução Francesa?', options: ['Século XVII', 'Século XVIII', 'Século XIX', 'Século XX'], answer: 'Século XVIII' },
  { subject: 'historia', question: 'Quem foi o líder da Revolução Russa de 1917?', options: ['Stalin', 'Trotsky', 'Lenin', 'Gorbachev'], answer: 'Lenin' },
  { subject: 'historia', question: 'Qual rainha britânica reinou por mais tempo?', options: ['Vitória', 'Elizabeth I', 'Elizabeth II', 'Mary I'], answer: 'Elizabeth II' },
  { subject: 'historia', question: 'Quem proclamou a Independência do Brasil?', options: ['Dom João VI', 'Dom Pedro I', 'Dom Pedro II', 'Tiradentes'], answer: 'Dom Pedro I' },
  { subject: 'historia', question: 'Qual o nome do navegador português que chegou às Índias por mar?', options: ['Vasco da Gama', 'Cabral', 'Bartolomeu Dias', 'Cristóvão Colombo'], answer: 'Vasco da Gama' },
  { subject: 'historia', question: 'Em que ano terminou a Primeira Guerra Mundial?', options: ['1914', '1916', '1918', '1920'], answer: '1918' },
];

const ciencias: Question[] = [
  { subject: 'ciencias', question: 'Qual o maior planeta do sistema solar?', options: ['Terra', 'Júpiter', 'Saturno', 'Marte'], answer: 'Júpiter' },
  { subject: 'ciencias', question: 'Qual o animal terrestre mais rápido?', options: ['Leão', 'Guepardo', 'Cavalo', 'Águia'], answer: 'Guepardo' },
  { subject: 'ciencias', question: 'Qual é o elemento químico mais abundante na crosta terrestre?', options: ['Oxigênio', 'Silício', 'Alumínio', 'Ferro'], answer: 'Oxigênio' },
  { subject: 'ciencias', question: 'Qual a fruta que, segundo a lenda, fez Newton descobrir a gravidade?', options: ['Laranja', 'Maçã', 'Pera', 'Uva'], answer: 'Maçã' },
  { subject: 'ciencias', question: 'Quantos ossos tem o corpo humano adulto?', options: ['206', '208', '210', '212'], answer: '206' },
  { subject: 'ciencias', question: 'Qual a cor primária da luz que não está no arco-íris percebido tradicional?', options: ['Vermelho', 'Amarelo', 'Azul', 'Verde'], answer: 'Verde' },
  { subject: 'ciencias', question: 'Qual o metal mais abundante na crosta terrestre?', options: ['Ferro', 'Alumínio', 'Cobre', 'Ouro'], answer: 'Alumínio' },
  { subject: 'ciencias', question: 'Qual a velocidade da luz no vácuo (aproximada)?', options: ['300.000 km/s', '150.000 km/s', '600.000 km/s', '1.000.000 km/s'], answer: '300.000 km/s' },
  { subject: 'ciencias', question: 'Quem criou a teoria da relatividade?', options: ['Isaac Newton', 'Albert Einstein', 'Galileu Galilei', 'Stephen Hawking'], answer: 'Albert Einstein' },
  { subject: 'ciencias', question: 'Qual é o maior órgão do corpo humano?', options: ['Fígado', 'Pulmão', 'Pele', 'Intestino'], answer: 'Pele' },
  { subject: 'ciencias', question: 'Quantos cromossomos tem o ser humano?', options: ['23', '44', '46', '48'], answer: '46' },
  { subject: 'ciencias', question: 'Qual o gás mais presente na atmosfera terrestre?', options: ['Oxigênio', 'Nitrogênio', 'Gás Carbônico', 'Hidrogênio'], answer: 'Nitrogênio' },
  { subject: 'ciencias', question: 'Quem descobriu a penicilina?', options: ['Louis Pasteur', 'Alexander Fleming', 'Marie Curie', 'Charles Darwin'], answer: 'Alexander Fleming' },
  { subject: 'ciencias', question: 'Qual o estado físico da água a 100°C ao nível do mar?', options: ['Sólido', 'Líquido', 'Gasoso', 'Plasma'], answer: 'Gasoso' },
  { subject: 'ciencias', question: 'Qual o símbolo químico do ouro?', options: ['Ou', 'Au', 'Go', 'Ag'], answer: 'Au' },
  { subject: 'ciencias', question: 'Qual a estrela mais próxima da Terra?', options: ['Sirius', 'Alfa Centauri', 'Sol', 'Polaris'], answer: 'Sol' },
  { subject: 'ciencias', question: 'Quantos planetas tem o sistema solar?', options: ['7', '8', '9', '10'], answer: '8' },
  { subject: 'ciencias', question: 'Qual o principal pigmento responsável pela cor verde das plantas?', options: ['Carotenoide', 'Clorofila', 'Antocianina', 'Xantofila'], answer: 'Clorofila' },
  { subject: 'ciencias', question: 'Em qual parte do corpo está o coração humano?', options: ['Abdômen', 'Tórax', 'Pescoço', 'Pelve'], answer: 'Tórax' },
  { subject: 'ciencias', question: 'Qual ciência estuda os seres vivos?', options: ['Física', 'Química', 'Biologia', 'Geologia'], answer: 'Biologia' },
];

const cultura: Question[] = [
  { subject: 'cultura', question: 'Quem escreveu "Dom Quixote"?', options: ['Machado de Assis', 'Miguel de Cervantes', 'Shakespeare', 'Fernando Pessoa'], answer: 'Miguel de Cervantes' },
  { subject: 'cultura', question: 'Quem pintou a Mona Lisa?', options: ['Vincent van Gogh', 'Leonardo da Vinci', 'Pablo Picasso', 'Michelangelo'], answer: 'Leonardo da Vinci' },
  { subject: 'cultura', question: 'Qual instrumento musical tem cordas e é tocado com arco?', options: ['Violão', 'Piano', 'Violino', 'Flauta'], answer: 'Violino' },
  { subject: 'cultura', question: 'Qual o nome da baleia do livro "Moby Dick"?', options: ['Orca', 'Flipper', 'Moby Dick', 'Willy'], answer: 'Moby Dick' },
  { subject: 'cultura', question: 'Qual animal é símbolo da paz?', options: ['Cachorro', 'Gato', 'Pomba', 'Leão'], answer: 'Pomba' },
  { subject: 'cultura', question: 'Quem escreveu "Os Lusíadas"?', options: ['Camões', 'Pessoa', 'Eça de Queirós', 'Saramago'], answer: 'Camões' },
  { subject: 'cultura', question: 'Quem pintou o teto da Capela Sistina?', options: ['Rafael', 'Michelangelo', 'Da Vinci', 'Caravaggio'], answer: 'Michelangelo' },
  { subject: 'cultura', question: 'Quem escreveu "Hamlet"?', options: ['Shakespeare', 'Goethe', 'Cervantes', 'Molière'], answer: 'Shakespeare' },
  { subject: 'cultura', question: 'Quem é o autor de "Capitães da Areia"?', options: ['Graciliano Ramos', 'Jorge Amado', 'Clarice Lispector', 'Guimarães Rosa'], answer: 'Jorge Amado' },
  { subject: 'cultura', question: 'Em qual museu está exposta a Mona Lisa?', options: ['Prado', 'Louvre', 'Uffizi', 'British Museum'], answer: 'Louvre' },
  { subject: 'cultura', question: 'Quem pintou "A Noite Estrelada"?', options: ['Monet', 'Van Gogh', 'Picasso', 'Dalí'], answer: 'Van Gogh' },
  { subject: 'cultura', question: 'Quem escreveu "O Pequeno Príncipe"?', options: ['Tolkien', 'Saint-Exupéry', 'Lewis Carroll', 'Andersen'], answer: 'Saint-Exupéry' },
  { subject: 'cultura', question: 'Quem escreveu "Memórias Póstumas de Brás Cubas"?', options: ['José de Alencar', 'Machado de Assis', 'Eça de Queirós', 'Jorge Amado'], answer: 'Machado de Assis' },
  { subject: 'cultura', question: 'De qual país são originários os Beatles?', options: ['Estados Unidos', 'Inglaterra', 'Irlanda', 'Austrália'], answer: 'Inglaterra' },
  { subject: 'cultura', question: 'Quem escreveu "Cem Anos de Solidão"?', options: ['Vargas Llosa', 'Borges', 'García Márquez', 'Cortázar'], answer: 'García Márquez' },
  { subject: 'cultura', question: 'Qual instrumento Chopin compunha principalmente?', options: ['Violino', 'Piano', 'Violoncelo', 'Órgão'], answer: 'Piano' },
  { subject: 'cultura', question: 'Quem compôs a 9ª Sinfonia?', options: ['Mozart', 'Beethoven', 'Bach', 'Vivaldi'], answer: 'Beethoven' },
  { subject: 'cultura', question: 'Qual dança é originária da Argentina?', options: ['Salsa', 'Tango', 'Samba', 'Bolero'], answer: 'Tango' },
  { subject: 'cultura', question: 'Quem escreveu "Iracema"?', options: ['José de Alencar', 'Machado de Assis', 'Castro Alves', 'Aluísio Azevedo'], answer: 'José de Alencar' },
  { subject: 'cultura', question: 'Qual o instrumento símbolo do rock and roll?', options: ['Piano', 'Guitarra elétrica', 'Saxofone', 'Bateria'], answer: 'Guitarra elétrica' },
];

const matematica: Question[] = [
  { subject: 'matematica', question: 'Quanto é 2 + 2?', options: ['3', '4', '5', '6'], answer: '4' },
  { subject: 'matematica', question: 'Quantos lados tem um hexágono?', options: ['5', '6', '7', '8'], answer: '6' },
  { subject: 'matematica', question: 'Quanto é 7 × 8?', options: ['54', '56', '64', '48'], answer: '56' },
  { subject: 'matematica', question: 'Quanto é a raiz quadrada de 81?', options: ['7', '8', '9', '10'], answer: '9' },
  { subject: 'matematica', question: 'Quantos lados tem um triângulo?', options: ['2', '3', '4', '5'], answer: '3' },
  { subject: 'matematica', question: 'Quantos lados tem um octógono?', options: ['6', '7', '8', '9'], answer: '8' },
  { subject: 'matematica', question: 'Quanto é 10²?', options: ['20', '100', '1.000', '10'], answer: '100' },
  { subject: 'matematica', question: 'Quanto é 1/2 + 1/4?', options: ['1/2', '2/4', '3/4', '1'], answer: '3/4' },
  { subject: 'matematica', question: 'Qual o valor aproximado de π (pi)?', options: ['2,71', '3,14', '1,41', '1,61'], answer: '3,14' },
  { subject: 'matematica', question: 'Qual o sucessor de 999?', options: ['998', '999', '1.000', '1.001'], answer: '1.000' },
  { subject: 'matematica', question: 'Na equação 2x + 4 = 10, qual o valor de x?', options: ['2', '3', '4', '5'], answer: '3' },
  { subject: 'matematica', question: 'Quanto é 25% de 200?', options: ['25', '40', '50', '75'], answer: '50' },
  { subject: 'matematica', question: 'Quanto é 15 × 4?', options: ['45', '50', '60', '70'], answer: '60' },
  { subject: 'matematica', question: 'Quantos zeros tem o número um milhão?', options: ['5', '6', '7', '9'], answer: '6' },
  { subject: 'matematica', question: 'Quanto é 144 ÷ 12?', options: ['10', '12', '14', '16'], answer: '12' },
  { subject: 'matematica', question: 'Qual o ângulo interno de um quadrado?', options: ['45°', '60°', '90°', '180°'], answer: '90°' },
  { subject: 'matematica', question: 'Quanto é 3³?', options: ['9', '12', '27', '81'], answer: '27' },
  { subject: 'matematica', question: 'Quanto é 100 − 37?', options: ['53', '63', '73', '67'], answer: '63' },
  { subject: 'matematica', question: 'Qual o próximo número primo depois de 7?', options: ['9', '10', '11', '13'], answer: '11' },
  { subject: 'matematica', question: 'Quantos lados tem um pentágono?', options: ['4', '5', '6', '7'], answer: '5' },
];

const esportes: Question[] = [
  { subject: 'esportes', question: 'Em qual esporte é usado o termo "home run"?', options: ['Beisebol', 'Críquete', 'Tênis', 'Golfe'], answer: 'Beisebol' },
  { subject: 'esportes', question: 'Quantos jogadores tem um time de futebol em campo?', options: ['9', '10', '11', '12'], answer: '11' },
  { subject: 'esportes', question: 'De quantos em quantos anos acontece a Copa do Mundo de futebol?', options: ['2', '3', '4', '5'], answer: '4' },
  { subject: 'esportes', question: 'Em qual país nasceu Pelé?', options: ['Argentina', 'Brasil', 'Portugal', 'Espanha'], answer: 'Brasil' },
  { subject: 'esportes', question: 'Quantos pontos vale uma cesta de três no basquete?', options: ['1', '2', '3', '4'], answer: '3' },
  { subject: 'esportes', question: 'Em qual esporte Michael Jordan é famoso?', options: ['Beisebol', 'Basquete', 'Futebol americano', 'Vôlei'], answer: 'Basquete' },
  { subject: 'esportes', question: 'Em qual esporte se usa cinturão para os campeões?', options: ['Boxe', 'Tênis', 'Atletismo', 'Natação'], answer: 'Boxe' },
  { subject: 'esportes', question: 'Qual esporte é conhecido como "esporte bretão"?', options: ['Rúgbi', 'Críquete', 'Futebol', 'Polo'], answer: 'Futebol' },
  { subject: 'esportes', question: 'Quantos jogadores tem um time de vôlei em quadra?', options: ['5', '6', '7', '8'], answer: '6' },
  { subject: 'esportes', question: 'Em qual esporte se usa raquete e peteca?', options: ['Tênis', 'Badminton', 'Squash', 'Ping-pong'], answer: 'Badminton' },
  { subject: 'esportes', question: 'Qual jogador ganhou mais Bolas de Ouro?', options: ['Cristiano Ronaldo', 'Messi', 'Pelé', 'Maradona'], answer: 'Messi' },
  { subject: 'esportes', question: 'Em qual país surgiu o judô?', options: ['China', 'Japão', 'Coreia', 'Tailândia'], answer: 'Japão' },
  { subject: 'esportes', question: 'Em qual esporte os atletas usam tacos sobre o gelo?', options: ['Patinação', 'Hóquei no gelo', 'Curling', 'Bobsled'], answer: 'Hóquei no gelo' },
  { subject: 'esportes', question: 'Em que ano o Brasil sediou sua primeira Copa do Mundo?', options: ['1938', '1950', '1962', '1970'], answer: '1950' },
  { subject: 'esportes', question: 'Em torneios de Grand Slam do tênis masculino, quantos sets ganha o vencedor?', options: ['2', '3', '4', '5'], answer: '3' },
  { subject: 'esportes', question: 'Onde foram realizados os primeiros Jogos Olímpicos modernos?', options: ['Roma', 'Atenas', 'Paris', 'Londres'], answer: 'Atenas' },
  { subject: 'esportes', question: 'Qual o esporte de Usain Bolt?', options: ['Natação', 'Atletismo', 'Ciclismo', 'Boxe'], answer: 'Atletismo' },
  { subject: 'esportes', question: 'Quantos minutos tem cada tempo regular de uma partida de futebol?', options: ['30', '40', '45', '50'], answer: '45' },
  { subject: 'esportes', question: 'Qual a cor da faixa mais alta no judô tradicional?', options: ['Vermelha', 'Preta', 'Marrom', 'Branca'], answer: 'Preta' },
  { subject: 'esportes', question: 'Em qual esporte é usado o termo "ace"?', options: ['Futebol', 'Tênis', 'Basquete', 'Boxe'], answer: 'Tênis' },
];

const portugues: Question[] = [
  { subject: 'portugues', question: 'Qual o plural de "cidadão"?', options: ['cidadãos', 'cidadões', 'cidades', 'cidadães'], answer: 'cidadãos' },
  { subject: 'portugues', question: 'Qual o plural de "pão"?', options: ['pãos', 'pães', 'panes', 'pãoes'], answer: 'pães' },
  { subject: 'portugues', question: 'Qual o feminino de "ator"?', options: ['atora', 'atriz', 'atra', 'atores'], answer: 'atriz' },
  { subject: 'portugues', question: 'Qual o coletivo de lobos?', options: ['Matilha', 'Alcateia', 'Cardume', 'Manada'], answer: 'Alcateia' },
  { subject: 'portugues', question: 'A qual classe gramatical pertence a palavra "rapidamente"?', options: ['Adjetivo', 'Substantivo', 'Advérbio', 'Verbo'], answer: 'Advérbio' },
  { subject: 'portugues', question: 'Qual o plural de "mal" (substantivo)?', options: ['mais', 'males', 'mauses', 'malos'], answer: 'males' },
  { subject: 'portugues', question: 'Qual a forma correta?', options: ['Esceção', 'Excessão', 'Exceção', 'Eccessão'], answer: 'Exceção' },
  { subject: 'portugues', question: 'Qual a forma correta?', options: ['Houveram muitos casos', 'Houve muitos casos', 'Houverão muitos casos', 'Houveram muitas casos'], answer: 'Houve muitos casos' },
  { subject: 'portugues', question: 'Qual destas é uma conjunção adversativa?', options: ['e', 'mas', 'porque', 'se'], answer: 'mas' },
  { subject: 'portugues', question: 'Qual destes é sinônimo de "feliz"?', options: ['Triste', 'Alegre', 'Pensativo', 'Calado'], answer: 'Alegre' },
  { subject: 'portugues', question: 'Qual o antônimo de "alto"?', options: ['Largo', 'Baixo', 'Magro', 'Profundo'], answer: 'Baixo' },
  { subject: 'portugues', question: 'Qual o aumentativo de "casa"?', options: ['Casinha', 'Casebre', 'Casarão', 'Casual'], answer: 'Casarão' },
  { subject: 'portugues', question: 'Qual o diminutivo de "flor"?', options: ['Floral', 'Florinha', 'Florzinha', 'Flozinha'], answer: 'Florzinha' },
  { subject: 'portugues', question: 'Qual a sílaba tônica da palavra "música"?', options: ['mú', 'si', 'ca', 'usi'], answer: 'mú' },
  { subject: 'portugues', question: 'Quantas sílabas tem a palavra "computador"?', options: ['3', '4', '5', '6'], answer: '4' },
  { subject: 'portugues', question: 'Qual a classe gramatical da palavra "azul"?', options: ['Substantivo', 'Adjetivo', 'Advérbio', 'Verbo'], answer: 'Adjetivo' },
  { subject: 'portugues', question: 'Qual o plural de "limão"?', options: ['limãos', 'limões', 'limãoes', 'limães'], answer: 'limões' },
  { subject: 'portugues', question: 'Qual destas frases está escrita corretamente?', options: ['Por que ele veio?', 'Porque ele veio?', 'Porquê ele veio?', 'Por quê ele veio?'], answer: 'Por que ele veio?' },
  { subject: 'portugues', question: 'Qual a forma correta da 1ª pessoa do verbo "saber" no presente?', options: ['sabo', 'sei', 'sabe', 'sabi'], answer: 'sei' },
  { subject: 'portugues', question: 'Qual destes é sinônimo de "começar"?', options: ['Encerrar', 'Iniciar', 'Pausar', 'Terminar'], answer: 'Iniciar' },
];

const cinema: Question[] = [
  { subject: 'cinema', question: 'Quem dirigiu o filme "Titanic"?', options: ['Steven Spielberg', 'James Cameron', 'Martin Scorsese', 'Ridley Scott'], answer: 'James Cameron' },
  { subject: 'cinema', question: 'Em qual filme aparece o personagem Forrest Gump?', options: ['Náufrago', 'Forrest Gump', 'Filadélfia', 'O Resgate do Soldado Ryan'], answer: 'Forrest Gump' },
  { subject: 'cinema', question: 'Em qual franquia aparece a frase "Que a Força esteja com você"?', options: ['Star Trek', 'Star Wars', 'Matrix', 'Guardiões da Galáxia'], answer: 'Star Wars' },
  { subject: 'cinema', question: 'Qual ator interpretou Harry Potter nos filmes?', options: ['Daniel Radcliffe', 'Rupert Grint', 'Tom Felton', 'Robert Pattinson'], answer: 'Daniel Radcliffe' },
  { subject: 'cinema', question: 'Em qual desenho animado aparece o leão Simba?', options: ['Madagascar', 'O Rei Leão', 'Tarzan', 'Mogli'], answer: 'O Rei Leão' },
  { subject: 'cinema', question: 'Em qual cidade se passa a série "Friends"?', options: ['Los Angeles', 'Chicago', 'Nova York', 'Boston'], answer: 'Nova York' },
  { subject: 'cinema', question: 'Quem dirigiu "E.T. — O Extraterrestre" e "Tubarão"?', options: ['George Lucas', 'Francis Ford Coppola', 'Steven Spielberg', 'Tim Burton'], answer: 'Steven Spielberg' },
  { subject: 'cinema', question: 'Qual o nome do mago em "O Senhor dos Anéis"?', options: ['Dumbledore', 'Merlin', 'Gandalf', 'Saruman'], answer: 'Gandalf' },
  { subject: 'cinema', question: 'Qual super-herói tem como alter ego Bruce Wayne?', options: ['Superman', 'Homem-Aranha', 'Batman', 'Flash'], answer: 'Batman' },
  { subject: 'cinema', question: 'Quem interpretou Jack em "Titanic"?', options: ['Brad Pitt', 'Leonardo DiCaprio', 'Tom Cruise', 'Matt Damon'], answer: 'Leonardo DiCaprio' },
  { subject: 'cinema', question: 'Qual ator interpreta Tony Stark / Homem de Ferro?', options: ['Chris Evans', 'Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo'], answer: 'Robert Downey Jr.' },
  { subject: 'cinema', question: 'Quem dirigiu "O Poderoso Chefão"?', options: ['Martin Scorsese', 'Francis Ford Coppola', 'Stanley Kubrick', 'Quentin Tarantino'], answer: 'Francis Ford Coppola' },
  { subject: 'cinema', question: 'Em qual cidade vive a família Simpson?', options: ['Quahog', 'Springfield', 'South Park', 'Bedrock'], answer: 'Springfield' },
  { subject: 'cinema', question: 'Quem é o vilão clássico do Batman?', options: ['Lex Luthor', 'Duende Verde', 'Coringa', 'Thanos'], answer: 'Coringa' },
  { subject: 'cinema', question: 'Qual o nome do reino em "Frozen"?', options: ['Genovia', 'Arendelle', 'Corona', 'Atlantis'], answer: 'Arendelle' },
  { subject: 'cinema', question: 'Qual personagem da Disney perdeu um sapatinho de cristal?', options: ['Branca de Neve', 'Bela', 'Cinderela', 'Aurora'], answer: 'Cinderela' },
  { subject: 'cinema', question: 'Em qual saga aparece a frase "Eu sou seu pai"?', options: ['Senhor dos Anéis', 'Star Wars', 'Harry Potter', 'Matrix'], answer: 'Star Wars' },
  { subject: 'cinema', question: 'Quem ganhou o Oscar de Melhor Ator por "O Discurso do Rei"?', options: ['Colin Firth', 'Geoffrey Rush', 'Anthony Hopkins', 'Daniel Day-Lewis'], answer: 'Colin Firth' },
  { subject: 'cinema', question: 'Qual ator interpreta o Capitão América nos filmes da Marvel?', options: ['Chris Pratt', 'Chris Evans', 'Chris Hemsworth', 'Sebastian Stan'], answer: 'Chris Evans' },
  { subject: 'cinema', question: 'Qual personagem de "Toy Story" é um cowboy?', options: ['Buzz', 'Woody', 'Rex', 'Slinky'], answer: 'Woody' },
];

export const questions: Question[] = [
  ...geografia,
  ...historia,
  ...ciencias,
  ...cultura,
  ...matematica,
  ...esportes,
  ...portugues,
  ...cinema,
];
